services:
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $DATABASE_USER_NAME
  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DATABASE_USER_NAME: $DATABASE_USER_NAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_PRODUCTION_NAME: $DATABASE_PRODUCTION_NAME
      DATABASE_HOST: $DATABASE_HOST
    volumes:
      - "./backend:/$WORKDIR"
    ports:
      - "3000:3000"
    depends_on:
      - db
