name: Vercel

on:
 push:
 on:
  pull_request:
    branches:
      - [develop]
    types:
      - closed

jobs:
 deploy:
   name: Deploy
   runs-on: ubuntu-latest
   permissions:
     contents: read
     deployments: write
     statuses: write
     pull-requests: write

   steps:
     - uses: actions/checkout@v4

     - uses: nexterias/actions-vercel@v1
       with:
         token: ${{ secrets.VERCEL_TOKEN }}
         org-id: ${{ secrets.VERCEL_ORG_ID }}
         project-id: ${{ secrets.VERCEL_PROJECT_ID }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
         production: ${{ github.ref == 'refs/heads/develop' }} 
